# server where jail runs
server-protocol: 'http'
server-socket: 'localhost:3346'
# where log processes
log-protocol: 'ws'
log-socket: 'localhost:3347'
# authorization server
auth-server-protocol: 'http'
auth-server-socket: 'localhost:3001'
# where images stored
# repository-protocol: 'http'
# repository-socket: 'localhost:3000'
repository-protocol: 'http'
repository-socket: 'localhost:3003'
# current jail configuration
jail-config: 'jmakefile.yml'
# to override default jail parameters
profile: undefined
